version: '3'

services:

  symfony:
    image: symfony:latest
    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=dev"
        - "BUILD_ARGUMENT_DEBUG_ENABLED=false"
      dockerfile: ./Dockerfile
    container_name: symfony
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=symfony
    ports:
      - "3306:3306"
    volumes:
      - ./var/mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
